version: "3"
services:
  elasticsearch:
    build: ./elasticsearch
    expose:
      - 9200

  frontend:
    build: ./frontend
    links:
      - elasticsearch
    ports:
      - 8000:8000
    volumes:
      - ./config:/config

  indexer:
    build: ./indexer
    links:
      - elasticsearch
    restart: on-failure
    volumes:
      - ./config:/config
